package dummydomain.yetanothercallblocker.data.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Date;

/**
 * DAO for table "BLACKLIST_ITEM".
 * <p>
 * Originally generated by the greenDAO Gradle plugin, which is not compatible
 * with Android Gradle Plugin 8+. Now maintained manually: keep in sync with {@link BlacklistItem}.
 */
public class BlacklistItemDao extends AbstractDao<BlacklistItem, Long> {

    public static final String TABLENAME = "BLACKLIST_ITEM";

    /**
     * Properties of entity BlacklistItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Pattern = new Property(2, String.class, "pattern", false, "PATTERN");
        public final static Property CreationDate = new Property(3, Date.class, "creationDate", false, "CREATION_DATE");
        public final static Property Invalid = new Property(4, boolean.class, "invalid", false, "INVALID");
        public final static Property NumberOfCalls = new Property(5, int.class, "numberOfCalls", false, "NUMBER_OF_CALLS");
        public final static Property LastCallDate = new Property(6, Date.class, "lastCallDate", false, "LAST_CALL_DATE");
    }

    public BlacklistItemDao(DaoConfig config) {
        super(config);
    }

    public BlacklistItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"BLACKLIST_ITEM\" (" +
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"PATTERN\" TEXT NOT NULL ," + // 2: pattern
                "\"CREATION_DATE\" INTEGER NOT NULL ," + // 3: creationDate
                "\"INVALID\" INTEGER NOT NULL ," + // 4: invalid
                "\"NUMBER_OF_CALLS\" INTEGER NOT NULL ," + // 5: numberOfCalls
                "\"LAST_CALL_DATE\" INTEGER);"); // 6: lastCallDate
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_BLACKLIST_ITEM_PATTERN ON \"BLACKLIST_ITEM\"" +
                " (\"PATTERN\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BLACKLIST_ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BlacklistItem entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindString(3, entity.getPattern());
        stmt.bindLong(4, entity.getCreationDate().getTime());
        stmt.bindLong(5, entity.getInvalid() ? 1L : 0L);
        stmt.bindLong(6, entity.getNumberOfCalls());

        Date lastCallDate = entity.getLastCallDate();
        if (lastCallDate != null) {
            stmt.bindLong(7, lastCallDate.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BlacklistItem entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindString(3, entity.getPattern());
        stmt.bindLong(4, entity.getCreationDate().getTime());
        stmt.bindLong(5, entity.getInvalid() ? 1L : 0L);
        stmt.bindLong(6, entity.getNumberOfCalls());

        Date lastCallDate = entity.getLastCallDate();
        if (lastCallDate != null) {
            stmt.bindLong(7, lastCallDate.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public BlacklistItem readEntity(Cursor cursor, int offset) {
        return new BlacklistItem( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
                cursor.getString(offset + 2), // pattern
                new Date(cursor.getLong(offset + 3)), // creationDate
                cursor.getShort(offset + 4) != 0, // invalid
                cursor.getInt(offset + 5), // numberOfCalls
                cursor.isNull(offset + 6) ? null : new Date(cursor.getLong(offset + 6)) // lastCallDate
        );
    }

    @Override
    public void readEntity(Cursor cursor, BlacklistItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPattern(cursor.getString(offset + 2));
        entity.setCreationDate(new Date(cursor.getLong(offset + 3)));
        entity.setInvalid(cursor.getShort(offset + 4) != 0);
        entity.setNumberOfCalls(cursor.getInt(offset + 5));
        entity.setLastCallDate(cursor.isNull(offset + 6) ? null : new Date(cursor.getLong(offset + 6)));
    }

    @Override
    protected final Long updateKeyAfterInsert(BlacklistItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    @Override
    public Long getKey(BlacklistItem entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BlacklistItem entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

}
