package dummydomain.yetanothercallblocker.data.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

/**
 * Originally generated by the greenDAO Gradle plugin, which is not compatible
 * with Android Gradle Plugin 8+. Now maintained manually.
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig blacklistItemDaoConfig;

    private final BlacklistItemDao blacklistItemDao;

    public DaoSession(Database db, IdentityScopeType type,
                      Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
        super(db);

        blacklistItemDaoConfig = daoConfigMap.get(BlacklistItemDao.class).clone();
        blacklistItemDaoConfig.initIdentityScope(type);

        blacklistItemDao = new BlacklistItemDao(blacklistItemDaoConfig, this);

        registerDao(BlacklistItem.class, blacklistItemDao);
    }

    public void clear() {
        blacklistItemDaoConfig.clearIdentityScope();
    }

    public BlacklistItemDao getBlacklistItemDao() {
        return blacklistItemDao;
    }

}
